import { fbPractica } from './styles/fonts'
import "./globals.css";

export const metadata = {
  title: "MTA App",
  description: "Generated by wiply",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning className={fbPractica.variable}>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
      </head>
      <body className="antialiased" suppressHydrationWarning>
        {children}
      </body>
    </html>
  );
}
